[package]
name = "pingora-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.80"
env_logger = "0.11.3"
log = "0.4.22"
pingora = { version = "0.2.0", features = ["lb"] }
rand = "0.8.5"
